// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using DisneyDown.Common.API.Schemas.MediaSchemas.PlaybackScenarioSchemaContainer;
//
//    var playbackScenarioSchema = PlaybackScenarioSchema.FromJson(jsonString);

using DisneyDown.Common.API.Schemas;
using DisneyDown.Common.API.Schemas.MediaSchemas.PlaybackScenarioSchemaContainer;

namespace DisneyDown.Common.API.Schemas.MediaSchemas.PlaybackScenarioSchemaContainer
{
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class PlaybackScenarioSchema
    {
        [JsonProperty("stream")]
        public Stream Stream { get; set; }

        [JsonProperty("tracking")]
        public Tracking Tracking { get; set; }

        [JsonProperty("playhead")]
        public Playhead Playhead { get; set; }

        [JsonProperty("thumbnails")]
        public Thumbnails Thumbnails { get; set; }
    }

    public partial class PlaybackScenarioSchema
    {
        public static PlaybackScenarioSchema FromJson(string json) => JsonConvert.DeserializeObject<PlaybackScenarioSchema>(json, ApiJsonConverter.Settings);
    }
}
