// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using DisneyDown.Common.API.Schemas.MediaSchemas.DmcVideoSchemaContainer;
//
//    var dmcVideoSchema = DmcVideoSchema.FromJson(jsonString);

namespace DisneyDown.Common.API.Schemas.MediaSchemas.DmcVideoSchemaContainer
{
    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class DmcVideoSchema
    {
        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class DmcVideoSchema
    {
        public static DmcVideoSchema FromJson(string json) => JsonConvert.DeserializeObject<DmcVideoSchema>(json, ApiJsonConverter.Settings);
    }
}
