// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using DisneyDown.Common.API.Schemas.MediaSchemas.DmcVideoBundleSchemaContainer;
//
//    var dmcVideoBundleSchema = DmcVideoBundleSchema.FromJson(jsonString);

namespace DisneyDown.Common.API.Schemas.MediaSchemas.DmcVideoBundleSchemaContainer
{
    using Newtonsoft.Json;

    public partial class DmcVideoBundleSchema
    {
        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class DmcVideoBundleSchema
    {
        public static DmcVideoBundleSchema FromJson(string json) => JsonConvert.DeserializeObject<DmcVideoBundleSchema>(json, DisneyDown.Common.API.Schemas.MediaSchemas.DmcVideoBundleSchemaContainer.Converter.Settings);
    }
}